project:
  type: website
  preview:
    port: 8000

website:
  title: "確率・統計基礎"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - slides.qmd
      - href: book/index.html
        text: Book

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


