project:
  type: website

website:
  title: "確率・統計基礎"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - book/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


