---
title: "確率論"
subtitle: "集合論と確率空間"
author: "森 立平"
format:
  revealjs:
    slide-number: true
    smaller: true
    html-math-method: mathjax
    include-in-header: macros.qmd
css: slides.css
---

## 確率論とは

::: {.wide-list}
- 世の中のランダムな事象を数学的に記述したもの。
- 統計・機械学習の基礎となっている。
- 確率論はコルモゴロフが1933年に導入した**測度論的確率論**によって定式化するのが一般的。
:::

<!--
極限定理: 確率 $p$ で表が出るコインを$N$ 回投げた時に、表が出る回数を $F$ とすると

::: {.wide-list}
- 大数の法則: $\frac{F}{N} \to p$
- 大偏差原理: $\Pr\left(\left|\frac{F}{N} - p\right| > \epsilon\right) = \mathrm{e}^{-\beta N}$
- 中心極限定理: $\frac{F-pN}{\sqrt{N}}\to$ 正規分布
:::
-->

## 統計学とは

**統計学**はデータから未来を予測したり意思決定をするための方法論。

- この薬は効果がありますか？
- このユーザーにどの製品が売れますか？
- この時間の道路の混雑具合は？

確率論は**統計学**の基礎となる。


## 確率論の数学モデルとは？

:::{.r-stack}
**測度論！**
:::

::: {.wide-list}
- 確率は面積($=$測度)のようなもの。
- 数学的に\textbf{厳密}に様々な結果(大数の法則、大偏差原理、中心極限定理)が証明できる。
- とても重要だが勉強するのは3年生以降(解析学要論Ⅱ、確率論)。
- この授業では**測度論には深入りせず、数学的に厳密な議論なごまかしながら確率・統計について学ぶ**。
:::

## この授業の進め方

::: {.wide-list}
- 講義資料は <https://prob-stat.github.io/> にすべてある。ここだけ見ればOK。
- その他の連絡事項はTACTを通じて行う。
- 毎回課題を出す。提出はTACTを用いる。
- 成績は**課題50% 期末試験50%**.
- 課題の内容と授業資料は上記のページにあるので、授業は出席しなくても構わない。
:::

## 集合

集合 $=$ 「ものの集まり」

\begin{align*}
A &= \{1,2,3\}&
B &= \{赤、青、黄、緑\}
\end{align*}

集合を構成するものを**要素**もしくは**元**という。

- $x\in A$: 要素 $x$ は集合 $A$ に含まれる。
- $x\notin A$: 要素 $x$ は集合 $A$ に含まない。
- $|A|$: 集合 $A$ の要素数

要素数が無限の集合を考えることもできる。
例えば

\begin{align*}
A&=\{n\in\mathbb{N}\mid \textsf{$n$ は偶数}\},& B&=\{x\in\mathbb{R}\mid \textsf{$x$ は無理数} \}
\end{align*}

という集合は無限集合の例となる。

- $\varnothing$: **空集合** $\coloneqq$ 要素数が 0 の集合 。

## 集合の関係

集合 $A$ の要素がすべて集合 $B$ に含まれるとき、$A$ を $B$ の**部分集合** という。

\begin{align*}
A\subseteq B &\defiff \forall x\,(x\in A\implies x \in B)&\textsf{($A$ は $B$ の部分集合)}\\
A\supseteq B &\defiff B\subseteq A&\textsf{($A$ は $B$ の上位集合)}\\
A = B &\defiff (A\subseteq B\land A\supseteq B)& \textsf{($A$ と $B$ は等しい)}\\
A \ne B &\defiff \lnot(A = B)& \textsf{($A$ と $B$ は等しくない)}
\end{align*}

また、

\begin{align*}
A\subsetneq B &\defiff (A\subseteq B \land A\ne B)&\textsf{($A$ は $B$ の真部分集合)}\\
A\supsetneq B &\defiff B\subsetneq A&\textsf{($A$ は $B$ の真上位集合)}
\end{align*}

とする。
部分集合や上位集合のような集合間の関係を**包含関係**という。
集合 $A,\,B$ について、$A\subseteq B$ と $B\subseteq A$ のどちらかが成り立つとき、「$A$ と $B$ の間に包含関係が成り立
つ」という。

包含関係は以下の三条件を満たす(半順序の公理)。

* (反射律) $\quad A\subseteq A$.
* (反対称律) $\quad (A\subseteq B\land B\subseteq A) \iff A = B$.
* (推移律) $\quad (A\subseteq B\land B\subseteq C)\implies A\subseteq C$.

## 集合の演算

複数の集合から新しい集合を作る演算がある。

\begin{align*}
A\cup B &\coloneqq\left\{x\mid x\in A \textsf{ または } x \in B\right\}\qquad\textsf{(和集合)}\\
A\cap B &\coloneqq \left\{x\mid x\in A \textsf{ かつ } x \in B\right\}\qquad\textsf{(積集合)}\\
A\setminus B &\coloneqq \left\{x\mid x\in A \textsf{ かつ } x \notin B\right\}\qquad\textsf{(差集合)}
\end{align*}

これらの演算は以下の法則を満たす。

* (交換法則) $\quad A\cup B = B\cup A, \quad A\cap B = B\cap A$.
* (結合法則) $\quad (A\cup B)\cup C = A\cup (B\cup C), \quad (A\cap B)\cap C=A\cap(B\cap C)$.
* (分配法則) $\quad A\cup(B\cap C) = (A\cup B)\cap (A\cup C),\quad A\cap (B\cup C) = (A\cap B)\cup (A\cap C)$.
* (冪等法則) $\quad A \cup A = A, \quad A\cap A = A$.
* (吸収法則) $\quad A \cup (A\cap B) = A, \quad A\cap (A\cup B) = A$.
* $A\cup \varnothing = A,\quad A\cap\varnothing = \varnothing$.

和集合と積集合は結合法則満たすことから、括弧を使わずに $A\cup B\cup C$ と表すことができる。

集合 $A$ と $B$ が $A\cap B=\varnothing$ を満たすとき、**確率論文脈では、「$A$ と $B$ は排反である」**(集合論文脈では「互いに素である」)という。

## 補集合

また、全体の集合 $\Omega$ というのが文脈上存在する場合は、

\begin{align*}
A^\mathrm{c} &\coloneqq \Omega\setminus A\qquad\textsf{(補集合)}
\end{align*}

と定義する。

**補集合**に関連して以下の法則を満たす。

* $\Omega^\mathrm{c} = \varnothing,\quad \varnothing^\mathrm{c} = \Omega$.
* $A\cup \Omega = \Omega,\quad A\cap\Omega = A$.
* $A\cup A^\mathrm{c} = \Omega,\quad A\cap A^\mathrm{c} =\varnothing$.
* (二重補集合の法則) $\quad (A^\mathrm{c})^\mathrm{c} = A$.
* (ド・モルガンの法則) $\quad(A\cup B)^\mathrm{c} = A^\mathrm{c} \cap B^\mathrm{c},\quad(A\cap B)^\mathrm{c} = A^\mathrm{c} \cup B^\mathrm{c}$


## 集合族

集合 $\Omega$ について $2^\Omega$ を $\Omega$ のすべての部分集合からなる集合を表す。

\begin{align*}
2^\Omega &\coloneqq \left\{A\subseteq\Omega\right\}.
\end{align*}

これを $\Omega$ の**冪集合**という。
例えば $\Omega=\{1,2,3\}$ のとき、

$$
2^\Omega = \left\{\varnothing, \{1\}, \{2\}, \{3\}, \{1,2\},\{2,3\},\{1,3\},\{1,2,3\}\right\}
$$

である。
$\Omega$ が有限集合のとき、$|2^\Omega|=2^{|\Omega|}$ が成り立つ。
また、$2^\Omega$ の部分集合を **$\Omega$ 上の(部分)集合族**と呼ぶ。
集合 $\Lambda$ の各 $\lambda\in\Lambda$ に対して集合 $A_\lambda\subseteq\Omega$ が存在するとき、集合族

$$
\left\{A_\lambda\subseteq\Omega\mid \lambda\in\Lambda\right\}\subseteq 2^\Omega
$$

を**添字集合 $\Lambda$ で添字付けられた $\Omega$ 上の集合族**という。

添字集合が有限集合の場合は集合族全体の和集合や積集合は二つの集合の和集合と積集合の定義を繰り返し用いることで定義できる。
それらは以下のように表す。

$$
\bigcup_{\lambda\in\Lambda} A_\lambda \quad,\quad
\bigcap_{\lambda\in\Lambda} A_\lambda.
$$

## ド・モルガンの法則

添字集合 $\Lambda$ が**無限集合**の場合は和集合と積集合を以下で定義する。

\begin{align*}
\bigcup_{\lambda\in\Lambda} A_\lambda
&\coloneqq
\left\{x\in\Omega\mid \exists \lambda\in\Lambda,\quad x\in A_\lambda\right\}\\
\bigcap_{\lambda\in\Lambda} A_\lambda
&\coloneqq
\left\{x\in\Omega\mid \forall \lambda\in\Lambda,\quad x\in A_\lambda\right\}
\end{align*}

この定義は $\Lambda$ が有限集合の場合も正しいものである。
この場合も**ド・モルガン**の法則は成り立つ。つまり、

\begin{align*}
\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&=
\bigcap_{\lambda\in\Lambda} A_\lambda^\mathrm{c},&
\left(\bigcap_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&=
\bigcup_{\lambda\in\Lambda} A_\lambda^\mathrm{c}
\end{align*}

が成り立つ。

証明:
$x\in\Omega$ について、
\begin{align*}
x\in\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)^\mathrm{c}
&\iff x\notin\left(\bigcup_{\lambda\in\Lambda} A_\lambda\right)\\
&\iff \lnot\left(\exists\lambda\in\Lambda,\quad x\in A_\lambda\right)\\
&\iff \forall\lambda\in\Lambda,\quad x\notin A_\lambda\\
&\iff \forall\lambda\in\Lambda,\quad x\in A_\lambda^\mathrm{c}\\
&\iff x\in\bigcap_{\lambda\in\Lambda} A_\lambda^{\mathrm{c}}.
\end{align*}

<!--
## 集合の濃度

集合の要素数を無限集合に一般化したものを集合の**濃度**という。
可算濃度
-->

## 標本空間と確率

- $\Omega\colon$ 集合。これの部分集合に確率が与えられる
- $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}.$ 確率を与える関数

::: {#exm-prob}

::: {.wide-list}

- $\Omega=\{表,裏\}$.
- $P(\varnothing)= 0,\, P(\{\mathrm{表}\})=P(\{\mathrm{裏}\})=\frac12,\,P(\{\mathrm{表},\mathrm{裏}\})=1$.

:::

::: {.wide-list}

- $\Omega=\{1,2,3,4,5,6\}$.
- $P(A) = \frac{|A|}6\quad\forall A\subseteq\Omega$.

:::

::: {.wide-list}

- $\Omega=\{晴,雨,雪\}$.
- $P(\varnothing)= 0,\, P(\{晴\})=0.7,\, P(\{雨\})=0.2,\,P(\{雪\})=0.1$,
$P(\{晴,雨\})=0.9,\, P(\{雨,雪\})=0.3,\, P(\{雪,晴\})=0.8$,
$P(\{晴,雨,雪\})=1$.

:::
:::

## 確率論の公理有限版

- $\Omega\colon$ **有限**集合(**標本空間**)
- $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}$ (**確率測度**)

確率の公理

1. $P(\Omega)=1$.
2. $\forall A, B\subseteq\Omega$, $A\cap B=\varnothing\implies P(A\cup B)=P(A)+P(B)$\ (**有限加法性**).

この公理を満たすペア $(\Omega,\, P)$ を**確率空間**という。

例えば

$$
   P(\{\text{"晴"}, \text{"雨"}\}) = P(\{\text{"晴"}\}) + P(\{\text{"雨"}\})
$$
という等式は「晴れもしくは雨になる確率 $=$ 晴れになる確率 $+$ 雨になる確率」という意味の等式になる。

このように $\Omega$ が有限集合の場合、**各 $\omega\in\Omega$ に対する一つの要素の確率 $P(\{\omega\})$ から $P$ が定まる**。

:::{.r-stack}
$\Omega$ を無限集合にしたい場合はどうする？
:::

## 確率論の公理可算版
- $\Omega\colon$ **高々可算**集合(**標本空間**)
- $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}$ (**確率測度**)

確率の公理

1. $P(\Omega)=1$.
<!-- 1. ~~$\forall A, B\subseteq\Omega$, $A\cap B=\varnothing\implies P(A\cup B)=P(A)+P(B)$\ (有限加法性).~~ -->
1. $\forall (A_n\subseteq\Omega)_{n\ge 0}$, $\forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n\ge0} A_n\right)=\sum_{n\ge0} P(A_n)$\ (**完全加法性, $\sigma$-加法性**).

無限和 $\sum_{n\ge0} P(A_n)$ において $P(A_n)\ge 0$ なので、この無限和が存在するときは**絶対収束**する。
よって和の順序を並び変えても収束値は変わらないことが分かる。実際、左辺にある $\bigcup_{n\ge 0} A_n$ は事象 $A_n$ の並び順によらない。

$\Omega$ が高々可算集合の場合、任意の $A\subseteq\Omega$ も高々可算集合なので、

\begin{align*}
P(A) &= P\left(\bigcup_{\omega\in A} \{\omega\}\right)\\
&= \sum_{\omega\in A} P(\{\omega\})
\end{align*}
が成り立つ。
よって**各 $\omega\in\Omega$ に対する一つの要素の確率 $P(\{\omega\})$ から $P$ が定まる**。

## 確率論の公理最終版?
これでよいのか？

- $\Omega\colon$ (**非可算**でもよい)集合(**標本空間**)
- $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}$ (**確率測度**)

確率の公理

1. $P(\Omega)=1$.
<!-- 2. ~~$\forall A, B\subseteq\Omega$, $A\cap B=\varnothing\implies P(A\cup B)=P(A)+P(B)$\ (有限加法性).~~ -->
3. $\forall (A_n\subseteq\Omega)_{n\ge 0}$, $\forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n\ge0} A_n\right)=\sum_{n\ge0} P(A_n)$\ (**完全加法性, $\sigma$-加法性**).

:::{.r-stack}
これで大丈夫？
:::


## ダメ(完全加法性+選択公理)

- $\Omega=[0,1)$.
- $\forall c\in\Omega,\, A\subseteq\Omega,\, P(A+c) = P(A)$ where $A+c\coloneqq\{a+c-\lfloor a+c\rfloor\mid a\in A\}$.

**選択公理を仮定するとそのような確率空間は存在しない**。

$\Omega$ の上の同値関係を
$x\sim y\stackrel{\mathrm{def}}{\iff} x-y \in\mathbb{Q}$と定義する。

$\Omega$ の上の同値類から一つずつ要素を選んで集合 $V$ を作る(**選択公理**)。

\begin{align*}
1 = P([0,1)) &= P\left(\bigcup_{x\in\mathbb{Q}} (V + x)\right)\\
&= \sum_{x\in\mathbb{Q}} P\left(V + x\right)\qquad\textsf{(完全加法性)}\\
&= \sum_{x\in\mathbb{Q}} P\left(V\right)\qquad\textsf{(平行移動不変性).}
\end{align*}
**同じ値を無限回足して1にはできない**。


## ちゃんとした確率論の公理
**確率空間** $(\Omega, \mathcal{F}, P)$

- $\Omega\colon$ 集合(**標本空間**)
- $\mathcal{F}\subseteq 2^\Omega$ (**事象の集合**、可測集合)
- $P\colon\mathcal{F}\to\mathbb{R}_{\ge 0}$ (**確率測度**、**確率は $\mathcal{F}$ の要素にのみ定義される！**)

可測集合 $\mathcal{F}$ の公理($\sigma$-加法族、完全加法族)

1. $\varnothing\in\mathcal{F}$.
2. $A\in\mathcal{F}\implies \Omega\setminus A\in\mathcal{F}$.
3. $(A_n\in\mathcal{F})_{n\ge 0}\implies \bigcup_{n\ge 0} A_n\in\mathcal{F}$ (完全加法性, $\sigma$-加
法性).

確率の公理

1. $P(\Omega)=1$.
2. $\forall (A_n\in\mathcal{F})_{n=1,\dotsc}$, $\forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n=1}^\infty A_n\right)=\sum_{n=1}^\infty P(A_n)$\ (完全加法性, $\sigma$-加法性).

つまり、**確率が定義される対象を $\mathcal{F}$ に限定**する。

さっきの例に現れた選択公理で作った集合 $V$ を $\mathcal{F}$ に含めなければ、矛盾なく確率を定義できる。

## この授業の方針
ここまでのまとめ

- $\Omega$ が高々可算の場合は $\mathcal{F}=2^\Omega$とできる。
- $\Omega$ が非可算の場合は(平行移動で不変などの条件を課すと)すべての部分集合を可測とできない場合がある
(要**選択公理**)。

この授業では **$\mathcal{F}=2^\Omega$のつもり**ですすめる。

$\Omega$ の部分集合を**事象**と呼ぶ。

実際に考えるような確率空間では非可測な集合$A\notin\mathcal{F}$は**選択公理**を使わないと構成できない。

普通に考える集合は**全部可測**。

この授業は測度論の授業ではないので、**非可測な集合については考えないことにする**。

今後、確率空間は $(\Omega,\,\mathcal{F},\,P)$ じゃなくて **$(\Omega,\,P)$** とする。


<!--
## 確率空間の例
離散的な確率空間

- $\Omega\colon$ 有限集合 or 可算無限集合.
- $P(A) = \sum_{k\in A} P(\{k\})$ ここで $\sum_{k\in\Omega} P(\{k\})=1$.

連続的な確率空間

- $\Omega=[0,1)\subseteq\mathbb{R}$
- $P([a,b)) = b-a$ から定まる.

連続的な確率空間

- $\Omega=\{\mathrm{H},\mathrm{T}\}^{\mathbb{N}}$.
- 任意の $n\in\mathbb{N}$ と $\eta\in\{\mathrm{H},\mathrm{T}\}^n$ について $P(\{\omega\in\Omega\mid \omega \textsf{ の最初の } n \textsf{ 個が } \eta\}) = \frac1{2^n}$.
-->

## 確率空間の性質

**確率空間** $(\Omega,\, P)$ と任意の $A,\,B\subseteq \Omega$ について以下が成り立つ。

1. $P(A^\mathrm{c}) = 1 - P(A)$.
2. $B\subseteq A\implies P(B)\le P(A)$
3. $P(A\cup B) = P(A) + P(B) - P(A\cap B)$.
4. $P(A\cup B) \le P(A) + P(B)\qquad$ (ブールの不等式、union bound).

::: {.proof}
1.
$$
1 = P(\Omega) = P(A \cup A^\mathrm{c}) = P(A) + P(A^\mathrm{c}).
$$

2.
$$
P(A) = P(B\cup (A\setminus B)) = P(B) + P(A\setminus B) \ge P(B).
$$

3.
\begin{align*}
P(A\cup B) &= P(A \cup (B\setminus A)) = P(A) + P(B\setminus A)\\
P(B) &= P((B\setminus A) \cup (A\cap B)) = P(B\setminus A) + P(A\cap B)
\end{align*}
より、 $P(B\setminus A)$ を消去することで得られる。

4.
3 より自明
:::

## ユニオンバウンド

::: {#lem-union}
## ユニオンバウンド

確率空間 $(\Omega,\, P)$ と $(A_n\subseteq\Omega)_{n\ge 0}$ について、
$$
P\left(\bigcup_{n\ge 0} A_n\right) \le \sum_{n\ge 0} P(A_n).
$$
:::
:::{.proof}

$B_0 \coloneqq A_0$, $B_n \coloneqq A_n \setminus \bigcup_{k=0}^{n-1} A_k$ とおくと、

\begin{align*}
P\left(\bigcup_{n\ge 0} A_n\right) &= P\left(\bigcup_{n\ge 0} B_n\right)\\
 &= \sum_{n\ge 0} P\left(B_n\right)\\
 &\le \sum_{n\ge 0} P\left(A_n\right).
\end{align*}
:::

## 確率測度の連続性

::: {#thm-cont}
## 確率測度の連続性

確率空間 $(\Omega,\, P)$ と事象列 $A_0\subseteq A_1\subseteq \dotsb \subseteq \Omega$ について
\begin{align*}
P\left(\bigcup_{n\ge 0} A_n\right) = \lim_{n\to\infty} P(A_n).
\end{align*}
また、事象列 $\Omega\supseteq A_0\supseteq A_1\supseteq \dotsb$ について
\begin{align*}
P\left(\bigcap_{n\ge 0} A_n\right) = \lim_{n\to\infty} P(A_n).
\end{align*}
:::
::: {.proof}
事象列 $A_0\subseteq A_1\subseteq \dotsb \subseteq \Omega$ について考える。
$B_0\coloneqq A_0$, $n\ge 1$について$B_n\coloneqq A_n\setminus A_{n-1}$とおく。
このとき、$i\ne j$について $B_i\cap B_j=\varnothing$。
また $k\ge 0$ について、$\bigcup_{n=0}^k B_n = \bigcup_{n=0}^kA_n = A_k$ が成り立つ.

\begin{align*}
P\left(\bigcup_{n\ge 0} A_n\right)&= P\left(\bigcup_{n\ge 0} B_n\right) =\sum_{n\ge 0} P(B_n)\\
&=\lim_{k\to\infty} \sum_{n=0}^k P(B_n)
=\lim_{k\to\infty} P\left(\bigcup_{n=0}^k B_n\right)
=\lim_{k\to\infty} P(A_k).
\end{align*}

事象列 $\Omega\supseteq A_0\supseteq A_1\supseteq \dotsb$ の場合についてはド・モルガンの法則を使うことで前半の結果に帰着でき証明できる。
:::

## 今週の課題

$\Omega = \{1,2,3,4,5,6\}$ とし、ある $P\colon\Omega\to\mathbb{R}_{\ge 0}$ について $(\Omega,\,P)$ を確率空間とする。
事象 $A,\,B,\,C$ を

\begin{align*}
A&=\left\{1,2,3,4\right\},&
B&=\left\{2,4,5\right\},&
C&=\left\{1,3,5,6\right\}
\end{align*}
とするとき、以下の問に答えよ

::: {.wide-list}

1. $A\cup B$,&nbsp; $A\cap B$,&nbsp; $A\setminus B$,&nbsp; $(A\cup B)\cap C$ をもとめよ。
1. $P(\{1,3\})$,&nbsp; $P(\{2,4\})$,&nbsp; $P(\{5\})$,&nbsp; $P(\{6\})$ を $P(A),\,P(B),\,P(C)$ を用いて表せ。

:::
