---
title: "確率論"
subtitle: "確率変数"
author: "森 立平"
format:
  revealjs:
    slide-number: true
    smaller: true
    html-math-method: mathjax
    include-in-header: macros.qmd
jupyter: python3
css: slides.css
---

## 確率空間の公理

確率空間 $(\Omega,\,P)$ の公理

- $\Omega\colon$ (**非可算**でもよい)集合(**標本空間**)
- $P\colon 2^\Omega\to\mathbb{R}_{\ge 0}$ (**確率測度**)


:::{.wide-list}
1. $P(\Omega)=1$.
<!-- 2. ~~$\forall A, B\subseteq\Omega$, $A\cap B=\varnothing\implies P(A\cup B)=P(A)+P(B)$\ (有限加法性).~~ -->
1. $\forall (A_n\subseteq\Omega)_{n\ge 0}$, $\forall i\ne j,\, A_i\cap A_j=\varnothing\implies P\left(\bigcup_{n\ge0} A_n\right)=\sum_{n\ge0} P(A_n)$\ (**完全加法性, $\sigma$-加法性**).
:::

:::{.r-stack}
本当は正しくないけど
:::

## 確率空間の例

一回のコイン投げ

:::{.wide-list}
- $\Omega = \{\mathrm{H},\mathrm{T}\}$.
- $P(A) = \frac{|A|}2\qquad\forall A\subseteq\Omega$.
:::

二回の独立なコイン投げ

:::{.wide-list}
- $\Omega = \{\mathrm{HH},\mathrm{HT},\mathrm{TH},\mathrm{TT}\}$.
- $P(A) = \frac{|A|}4\qquad\forall A\subseteq\Omega$.
:::

無限回の独立なコイン投げ

:::{.wide-list}
- $\Omega = \{\mathrm{H},\mathrm{T}\}^{\mathbb{N}}$.
- $P(A) = \frac{|A|}4\qquad\forall A\subseteq\Omega$.
:::

実数

:::{.wide-list}
- $\Omega = [0,1)$.
- $P([a,b)) = b-a\qquad\forall A\subseteq\Omega$.
:::

## 確率変数
実際に知りたい情報は限定されている。

$100$ 回コインを投げると $2^{100}$ 通りの結果があるが、興味がある情報は例えば以下のものなど。

:::{.wide-list}
- $k$ 回目に表が出たか裏が出たか
- 表が出た回数
- 二回連続同じ面が出た回数
- 連続して何回表が出たか
:::

:::{.definition}

**確率変数**

$(\Omega,\,P)$ を確率空間とするとき、関数 $X\colon \Omega\to\mathbb{R}$ を確率変数とよぶ。
また、実数 $a\in\mathbb{R}$ について
\begin{align*}
\Pr(X\le a) &\coloneqq P(\left\{\omega\in\Omega\mid X(\omega)\le a\right\})
\end{align*}
と表す。
$\Pr(X\ge a),\,\Pr(X=a),\,\Pr(X<a),\,\Pr(X>a)$ なども同様に定義される。

:::

例えば、$\Omega=\{\mathrm{HH},\mathrm{HT},\mathrm{TH},\mathrm{TT}\}$ のとき、.

\begin{align*}
X_1(\mathrm{HH}) &= X_1(\mathrm{HT}) = 1,& X_1(\mathrm{TH}) = X_1(\mathrm{TT}) = 0\\
X_2(\mathrm{HH}) &= X_2(\mathrm{TH}) = 1,& X_2(\mathrm{HT}) = X_2(\mathrm{TT}) = 0\\
X&=X_1+X_2
\end{align*}

## 累積分布関数

確率変数 $X$ の**累積分布関数 (cumulative distribution function)**

\begin{align*}
F_X(x) &\coloneqq \Pr(X\le x)\qquad\forall x\in\mathbb{R}
\end{align*}

累積分布関数は定義より**単調非減少**関数であることが分かる。
累積分布関数は連続とは限らないが**右連続**であることは以下のように確認できる。

\begin{align*}
\lim_{n\to\infty} \Pr\left(X \le x + \frac1n\right) &=
\lim_{n\to\infty} P\left(\left\{\omega\in\Omega\mid X(\omega) \le x + \frac1n\right\}\right)\\
&= P\left(\bigcap_{n=1}^\infty \left\{\omega\in\Omega\mid X(\omega) \le x + \frac1n\right\}\right)\\
&= P\left(\left\{\omega\in\Omega\mid X(\omega) \le x\right\}\right)\\
&= \Pr\left(X\le x\right).
\end{align*}

累積分布関数は以下の性質を持つ。

1. $F_X$ は単調非減少。
1. $F_X$ は右連続。
1. $\lim_{x\to\infty}F_X(x) = 1$.
1. $\lim_{x\to-\infty}F_X(x) = 0$.

逆にこれらの性質を満たしていれば、何かしらの確率変数 $X$ の累積分布関数とみなせる。

## 累積分布関数の例


**二項分布** $\mathrm{Binomial}(n,p)\colon$
表が出る確率が $p\in[0,1]$ のコインを独立に $n$ 回投げて表が出る回数

\begin{align*}
\Pr(X=k) &= \binom{n}{k} p^k(1-p)^{n-k}\qquad\forall k\in\{0,1,\dotsc,n\}\\
F_X(k) &= \sum_{i=0}^k \binom{n}{i} p^i(1-p)^{n-i}.
\end{align*}

```{python}
#| layout-ncol: 1
#| label: fig-binom-cdf
#| fig-cap:
#|  - "二項分布の累積分布関数"

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 12       # 試行回数
p = 0.6      # 成功確率

# 取りうる値の範囲
x = np.arange(0, n+1)

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット

plt.figure(figsize=(8, 4))
plt.step(x, cdf, where='post')
plt.xticks(x)
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```


## 離散型確率変数

**離散型確率変数**: 像が高々可算無限の確率変数

任意の $A\subseteq\mathrm{Image}(X)$ について、
\begin{align*}
\Pr(X\in A) &= P\left(\{\omega\in\Omega\mid X(\omega)\in A\}\right)\\
&= P\left(\bigcup_{x\in A} \{\omega\in\Omega\mid X(\omega)=x\}\right)\\
&= \sum_{x\in A} P\left(\{\omega\in\Omega\mid X(\omega)=x\}\right)\\
&= \sum_{x\in A} \Pr\left(X=x\right)
\end{align*}

**確率質量関数 (probability mass function)**
\begin{align*}
f_X(x)&\coloneqq \Pr(X=x)\qquad\forall x\in\mathbb{R}.
\end{align*}

すると
\begin{align*}
\Pr(X\in A) &= \sum_{x\in A} f_X(x).
\end{align*}

## 確率質量関数の例

**二項分布** $\mathrm{Binomial}(n,p)\colon$

\begin{align*}
f_X(k) &= \binom{n}{k} p^k(1-p)^{n-k}.
\end{align*}

```{python}
#| layout-ncol: 1
#| label: fig-binom
#| fig-cap:
#|  - "二項分布の確率質量関数"

import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 12       # 試行回数
p = 0.6      # 成功確率

# 取りうる値の範囲
x = np.arange(0, n+1)

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(8, 4))
plt.bar(x, pmf, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```
  

## 連続型確率変数

**連続型確率変数**: 離散型確率変数でない確率変数


**確率密度関数 (probability density function)**
\begin{align*}
\Pr(X\in A) &= \int_{A} f_X(x) \mathrm{d}x.
\end{align*}
を満たす関数 $f_X\colon\mathbb{R}\to\mathbb{R}_{\ge 0}$.
離散確率変数に対する
\begin{align*}
\Pr(X\in A) &= \sum_{x\in A} f_X(x)
\end{align*}

と同じ形。

一般的には確率密度関数は**存在するとは限らない**。


累積分布関数 $F_X(x)$ が**微分可能**なとき、
\begin{align*}
f_X(x) &= \frac{\mathrm{d} F_X}{\mathrm{d}x}
\end{align*}

とおくと
\begin{align*}
\int_{-\infty}^x f_X(z) \mathrm{d}z &= F_X(x)
\end{align*}
を満たす。
累積分布関数が連続で微分不可能な点が飛び飛びにある場合も確率密度関数は $f_X = F_X'$ と取れる。
累積分布関数が微分不可能な点は確率密度関数の値を任意に決めてよい。


## 連続確率変数の例

**正規分布(ガウス分布)** $N(\mu,\sigma)\colon$

\begin{align*}
f_X(x) &= \frac1{\sqrt{2\pi\sigma^2}}\mathrm{e}^{-\frac{(x-\mu)^2}{2\sigma^2}},&
F_X(x) &= \int_{-\infty}^x \frac1{\sqrt{2\pi\sigma^2}}\mathrm{e}^{-\frac{(z-\mu)^2}{2\sigma^2}}\mathrm{d}z
\end{align*}

特に $\mu=0$, $\sigma=1$ のとき**標準正規分布**という。

```{python}
#| layout-ncol: 2
#| label: fig-normal-0
#| fig-cap:
#|  - "標準正規分布の確率密度関数"
#|  - "標準正規分布の累積分布関数"

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

# パラメータの設定

# 取りうる値の範囲
x = np.linspace(norm.ppf(0.001), norm.ppf(0.999), 100)

# 一様分布のPMFの計算
pdf = norm.pdf(x)
cdf = norm.cdf(x)

# プロット
plt.figure(figsize=(6, 3))
plt.plot(x, pdf)
plt.title(f'PDF of normal distribution with $\\mu = 0$ and $\\sigma = 1$')
plt.xlabel('$x$')
plt.ylabel('$f_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.plot(x, cdf)
plt.title(f'CDF of normal distribution with $\\mu = 0$ and $\\sigma = 1$')
plt.xlabel('$x$')
plt.ylabel('$F_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 離散確率変数の例

* **二項分布** $\mathrm{Binomial}(n,p)$: 表が出る確率が $p$ のコインを $n$ 回独立に投げたとき、表が出る回数の分布
$$\Pr(X=k) = \binom{n}{k} p^k (1-p)^{n-k}.$$
* **幾何分布** $\mathrm{Geometric}(p)$: 表が出るまでに投げるコインの回数の分布
$$\Pr(X=k) = (1-p)^{k-1}p.$$
* **超幾何分布** $\mathrm{HyperGeometric}(N,K,n)$: 袋の中に $N$ 個のボールがあって、そのうち $K$ 個が当たりとし、 $n$ 個引いたときの当たりの個数の分布
$$\Pr(X=k) = \frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}}.$$
* **ポアソン分布** $\mathrm{Poisson}(\lambda)$:
$$
\Pr(X=k) = \frac{\lambda^k}{k!}\mathrm{e}^{-\lambda}.
$$

## 幾何分布

**幾何分布** $\mathrm{Geometric}(p)$: 表が出る確率が $p\in[0,1]$ のコインを独立に何度も投げて表が出るまでに投げる回数

$$
f_X(k) = (1-p)^{k-1}p,\qquad\forall k\ge 1
$$

```{python}
#| layout-ncol: 2
#| label: fig-geom
#| fig-cap:
#|  - "幾何分布の確率質量関数"
#|  - "幾何分布の累積分布関数"

import numpy as np
from scipy.stats import geom
import matplotlib.pyplot as plt

# パラメータの設定
n = 12       # 試行回数
p = 0.6      # 成功確率

# 取りうる値の範囲
k = np.arange(1, n+1)
kk = np.arange(0, n+1)

# 幾何分布のPMFの計算
pmf = geom.pmf(k, p)
cdf = geom.cdf(kk, p)

# プロット
plt.figure(figsize=(6, 3))
plt.bar(k, pmf, tick_label=k)
plt.title(f'PMF of geometric distribution with p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.step(kk, cdf, where='post')
plt.xticks(kk)
plt.title(f'CDF of geometric distribution with p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 超幾何分布

**超幾何分布** $\mathrm{HyperGeometric}(N,K,n)$: 袋の中に $N$ 個のボールがあって、そのうち $K$ 個が当たりとし、 $n$ 個引いたときの当たりの個数

$$
f_X(k) = \frac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}},\qquad\forall k\in \{0,\dotsc,\min\{K, n\}\}
$$

```{python}
#| layout-ncol: 2
#| label: fig-hypergeom
#| fig-cap:
#|  - "超幾何分布の確率質量関数"
#|  - "超幾何分布の累積分布関数"

import numpy as np
from scipy.stats import hypergeom
import matplotlib.pyplot as plt

# パラメータの設定
N = 40
n = 16
K = 12

# 取りうる値の範囲
k = np.arange(0, K+1)

# 超幾何分布のPMFの計算
pmf = hypergeom.pmf(k, N, K, n)
cdf = hypergeom.cdf(k, N, K, n)

# プロット
plt.figure(figsize=(6, 3))
plt.bar(k, pmf, tick_label=k)
plt.title(f'PMF of hypergeometric distribution with K={K}, N={N}, n = {n}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.step(k, cdf, where='post')
plt.xticks(k)
plt.title(f'CDF of hypergeometric distribution with K={K}, N={N}, n = {n}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## ポアソン分布

正のパラメータ $\lambda\in\mathbb{R}_{>0}$ について、**ポアソン分布** $\mathrm{Poisson}(\lambda)$ の確率質量関数は

$$
f_X(k) = \frac{\lambda^k}{k!}\mathrm{e}^{-\lambda},\qquad \forall k\ge 0.
$$

```{python}
#| layout-ncol: 2
#| label: fig-poisson
#| fig-cap:
#|  - "ポアソン分布の確率質量関数"
#|  - "ポアソン分布の累積分布関数"

import numpy as np
from scipy.stats import poisson
import matplotlib.pyplot as plt

# パラメータの設定
lam = 5

# 取りうる値の範囲
k = np.arange(0, 3*lam)

# ポアソン分布のPMFの計算
pmf = poisson.pmf(k, lam)
cdf = poisson.cdf(k, lam)

# プロット
plt.figure(figsize=(6, 3))
plt.bar(k, pmf, tick_label=k)
plt.title(f'PMF of Poisson distribution with $\\lambda$={lam}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.step(k, cdf, where='post')
plt.xticks(k)
plt.title(f'CDF of Poisson distribution with $\\lambda$={lam}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 一様分布

実数 $a<b$ について、**一様分布** $\mathrm{U}(a,b)$ の確率密度関数と累積分布関数は

\begin{align*}
f_X(x) &= \begin{cases}
\frac1{b-a}& \text{if } x\in[a,b]\\
0&\text{otherwise}
\end{cases},&
F_X(x) &= \begin{cases}
0&\text{if } x < a\\
\frac{x-a}{b-a}&\text{if } x \in[a,b]\\
1&\text{otherwise.}
\end{cases}
\end{align*}

```{python}
#| layout-ncol: 2
#| label: fig-uniform
#| fig-cap:
#|  - "一様分布の確率密度関数"
#|  - "一様分布の累積分布関数"

import numpy as np
from scipy.stats import uniform
import matplotlib.pyplot as plt

# パラメータの設定

# 取りうる値の範囲
#x = np.linspace(uniform.ppf(0.01), uniform.ppf(0.99), 100)
x = np.linspace(-0.1, +1.1, 1000)

# 一様分布のPMFの計算
pdf = uniform.pdf(x)
cdf = uniform.cdf(x)

# プロット
plt.figure(figsize=(6, 3))
plt.plot(x, pdf)
plt.title(f'PDF of Uniform distribution on $[0,1]$')
plt.xlabel('$x$')
plt.ylabel('$f_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.plot(x, cdf)
plt.title(f'CDF of Uniform distribution on $[0,1]$')
plt.xlabel('$x$')
plt.ylabel('$F_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 正規分布 (ガウス分布)

パラメータ $\mu\in\mathbb{R},\,\sigma\in\mathbb{R}_{>0}$ について、**正規分布** $N(\mu,\sigma)$ の確率密度関数と累積分布関数は
\begin{align*}
f_X(x) &= \frac1{\sqrt{2\pi\sigma^2}}\mathrm{e}^{-\frac{(x-\mu)^2}{2\sigma^2}},&
F_X(x) &= \int_{-\infty}^x \frac1{\sqrt{2\pi\sigma^2}}\mathrm{e}^{-\frac{(z-\mu)^2}{2\sigma^2}}\mathrm{d}z.
\end{align*}

特に $\mu=0$, $\sigma=1$ のとき**標準正規分布**という。

```{python}
#| layout-ncol: 2
#| label: fig-normal
#| fig-cap:
#|  - "標準正規分布の確率密度関数"
#|  - "標準正規分布の累積分布関数"

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt

# パラメータの設定

# 取りうる値の範囲
x = np.linspace(norm.ppf(0.001), norm.ppf(0.999), 100)

# 一様分布のPMFの計算
pdf = norm.pdf(x)
cdf = norm.cdf(x)

# プロット
plt.figure(figsize=(6, 3))
plt.plot(x, pdf)
plt.title(f'PDF of normal distribution with $\\mu = 0$ and $\\sigma = 1$')
plt.xlabel('$x$')
plt.ylabel('$f_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.plot(x, cdf)
plt.title(f'CDF of normal distribution with $\\mu = 0$ and $\\sigma = 1$')
plt.xlabel('$x$')
plt.ylabel('$F_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 指数分布

パラメータ $\lambda\in\mathbb{R}_{>0}$ について、**指数分布** $\mathrm{Exp}(\lambda)$ の確率密度関数と累積分布関数は

\begin{align*}
f_X(x) &= \begin{cases}
0&\text{if } x < 0\\
\lambda\mathrm{e}^{-\lambda x}&\text{otherwise}
\end{cases},&
F_X(x) &= \begin{cases}
0&\text{if } x < 0\\
1-\mathrm{e}^{-\lambda x}&\text{otherwise}
\end{cases}
\end{align*}

```{python}
#| layout-ncol: 2
#| label: fig-exp
#| fig-cap:
#|  - "指数分布の確率密度関数"
#|  - "指数分布の累積分布関数"

import numpy as np
from scipy.stats import expon
import matplotlib.pyplot as plt

# パラメータの設定

# 取りうる値の範囲
x = np.linspace(expon.ppf(0.001), expon.ppf(0.999), 100)

# PMFの計算
pdf = expon.pdf(x)
cdf = expon.cdf(x)

# プロット
plt.figure(figsize=(6, 3))
plt.plot(x, pdf)
plt.title(f'PDF of exponential distribution with $\\lambda = 1$')
plt.xlabel('$x$')
plt.ylabel('$f_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(6, 3))
plt.plot(x, cdf)
plt.title(f'CDF of exponential distribution with $\\lambda = 1$')
plt.xlabel('$x$')
plt.ylabel('$F_X(x)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 確率変数、確率分布、確率空間


確率変数 $X$ の累積分布関数が○○分布の累積分布関数と等しいとき、
「**確率変数 $X$ は○○分布に従う**」という。

例えば「確率変数 $X$ は二項分布 $\mathrm{Binomial}(n,p)$ に従う」という。
このとき、$X\sim\mathrm{Binomial}(n,p)$ と表す。

<br>

**確率空間を陽に定義しないで確率変数を考える**ことも多い。
確率変数が特定の値を取る確率を解析したいときには確率空間の定義は不要。

<br>

離散型確率変数は自然に説明できるものが多いので、自然な確率空間を考えることができることが多い。

* 二項分布: $n$ 回のコイン投げ、もしくは無限回のコイン投げ。
* 幾何分布: 無限回のコイン投げ。
* 超幾何分布: $K$ 個の当たりと $N-K$ 個のはずれのボールの $\binom{N}{K}$ 通りの並び順。
* ポアソン分布: ？

<br>

今後は主に確率変数を用いた確率の解析をしていく。
**確率空間を陽に考えることは少ない**。

<!--
複数の確率変数を同時に考えるときは、共通の確率空間が必要なのでこのような自然な確率空間を考えることもある。
-->

## $X+a$ の確率密度関数

::: {#lem-pdf-add}
確率密度関数を持つ任意の確率変数 $X$ と $a\in\mathbb{R}$ について、
\begin{align*}
f_{X+a}(x) &= f_X(x-a)
\end{align*}
は $X+a$ の確率密度関数になる。
:::
::: {.proof}
関数 $f_Z\colon \mathbb{R}\to\mathbb{R}_{\ge 0}$ が

$$
\Pr(Z\le x) = \int_{-\infty}^x f_Z(z)\mathrm{d} z
$$

を満たすとき、$f_Z$ は確率変数 $Z$ の確率密度関数となる。

任意の $a\in\mathbb{R}$ について、
\begin{align*}
\Pr(X+a\le x) &= \Pr(X\le x-a)\\
&= \int_{-\infty}^{x-a} f_{X}(z)\mathrm{d}z\\
&= \int_{-\infty}^{x} f_{X}(z'-a)\mathrm{d}z'\qquad (z'=z+a).
\end{align*}
:::

## $aX$ の確率密度関数

::: {#lem-pdf-mul}
確率密度関数を持つ任意の確率変数 $X$ と $a\in\mathbb{R}_{\ne 0}$ について、
\begin{align*}
f_{aX}(x) &= \frac1{|a|} f_X(x/a)
\end{align*}
は $aX$ の確率密度関数になる。
:::
::: {.proof}
関数 $f_Z\colon \mathbb{R}\to\mathbb{R}_{\ge 0}$ が

$$
\Pr(Z\le x) = \int_{-\infty}^x f_Z(z)\mathrm{d} z
$$

を満たすとき、$f_Z$ は確率変数 $Z$ の確率密度関数となる。

任意の $a>0$ について、
\begin{align*}
\Pr(aX\le x) &= \Pr(X\le x/a)\\
&= \int_{-\infty}^{x/a} f_{X}(z)\mathrm{d}z\\
&= \int_{-\infty}^{x} \frac1{a} f_{X}(z'/a)\mathrm{d}z'\qquad (z'=az).
\end{align*}
$a<0$ についても同様。
:::

## $g(X)$ の確率密度関数

::: {#lem-pdf-inc}
$J\subseteq\mathbb{R}$ を有界とは限らない区間とし、$g\colon J\to\mathbb{R}$ を $J$ の内点で**微分可能**で $g'(x)>0$ とする。
確率密度関数を持つ任意の確率変数 $X$ について、
\begin{align*}
f_{g(X)}(x) &=
\begin{cases}
\frac1{g'(g^{-1}(x))} f_X(g^{-1}(x))&\text{if } x\in\mathrm{Image}(g)\\
0&\text{otherwise.}
\end{cases}
\end{align*}
は $g(X)$ の確率密度関数になる。
:::
::: {.proof}
関数 $f_Z\colon \mathbb{R}\to\mathbb{R}_{\ge 0}$ が

$$
\Pr(Z\le x) = \int_{-\infty}^x f_Z(z)\mathrm{d} z
$$

を満たすとき、$f_Z$ は確率変数 $Z$ の確率密度関数となる。

任意の $x\in\mathrm{Image}(g)$ について
\begin{align*}
\Pr(g(X)\le x) &= \Pr(X\le g^{-1}(x))\\
&= \int_{-\infty}^{g^{-1}(x)} f_{X}(z)\mathrm{d}z\\
&= \int_{\inf \mathrm{Image}(g)}^{x} f_{X}(g^{-1}(z')) \frac1{g'(g^{-1}(z'))}\mathrm{d}z'\qquad (z'=g(z)).
\end{align*}
:::

<!--
## 累積分布関数の逆関数

確率変数 $X$ の累積分布関数 $F_X$ は以下の性質を持っていた。

1. $F_X$ は単調非減少。
1. $F_X$ は右連続。
1. $\lim_{x\to\infty}F_X(x) = 1$.
1. $\lim_{x\to-\infty}F_X(x) = 0$.
-->

## 今週の課題


以下の問に答えよ

::: {.wide-list}

1. $\Pr(X=1) = 0.2,\,\Pr(X=2)=0.1,\,\Pr(X=3)=0.7$ を満たす確率変数 $X$ の累積分布関数 $F_X(x)$ を $[0,4]$ の区間で図示せよ。不連続点で取る値が分かるようにすること。
1. $U\sim\mathrm{U}(0,1)$ とする。このとき、$-2\log U$ の確率密度関数をもとめよ。すべての $\mathbb{R}$ に対する値を示すこと。

:::
