---
title: "確率論"
subtitle: "中心極限定理"
author: "森 立平"
format:
  revealjs:
    slide-number: true
    smaller: true
    html-math-method: mathjax
    include-in-header: macros.qmd
css: slides.css
---


## 大数の法則と確率の集中
```{python}
#| layout-ncol: 1
#| label: fig-binom-10
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 10       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(0, n+1)

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(0, n+1, n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(0, n+1, n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 大数の法則と確率の集中
```{python}
#| layout-ncol: 1
#| label: fig-binom-100
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 100       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(0, n+1)

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(0, n+1, n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(0, n+1, n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 大数の法則と確率の集中
```{python}
#| layout-ncol: 1
#| label: fig-binom-1000
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 1000       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(0, n+1)

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(0, n+1, n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(0, n+1, n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 期待値周辺
```{python}
#| layout-ncol: 1
#| label: fig-binom-clt-10
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 10       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))))

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 期待値周辺
```{python}
#| layout-ncol: 1
#| label: fig-binom-clt-100
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 100       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))))

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 期待値周辺
```{python}
#| layout-ncol: 1
#| label: fig-binom-clt-1000
#| fig-cap:
#|  - "二項分布の確率質量関数"
#|  - "二項分布の累積分布関数"


import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import binom

# パラメータの設定
n = 1000       # 試行回数
p = 0.3      # 成功確率

# 取りうる値の範囲
x = np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))))

# 二項分布のPMFの計算
pmf = binom.pmf(x, n, p)
cdf = binom.cdf(x, n, p)

# プロット
plt.figure(figsize=(5, 2.5))
plt.bar(x, pmf, width=0.9, tick_label=x)
plt.title(f'PMF of binomial distribution with n={n}, p={p}')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X=k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

plt.figure(figsize=(5, 2.5))
plt.step(x, cdf, where='post')
plt.xticks(np.arange(int(round(n*p-2*np.sqrt(n))), int(round(n*p+2*np.sqrt(n))), n//10))
plt.title(f'CDF of binomial distribution with n={n}, p={p}')
plt.xlabel('$k$')
plt.ylabel('$\\Pr(X\\leq k)$')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()
```

## 法則収束

::: {#def-converge-law}
### 確率変数の法則収束
確率変数の列 $(X_n)_{n=1,2,\dotsc,}$ を考える。これらの確率変数は確率空間 $(\Omega,\,P)$ を共有している必要はない(同時確率を考えるわけではないので)。
確率変数の列 $(X_n)_{n=1,2,\dotsc,}$ が確率変数 $X$ に**法則収束**する $\defiff$
$X$ の累積分布関数 $F_X$ のすべての連続点 $x\in\mathbb{R}$ について
\begin{align*}
\lim_{n\to\infty} F_{X_n}(x)= F_X(x)
\end{align*}

また、このとき $X_n\overset{d}{\to} X$ と表す。
:::


## 中心極限定理

::: {#thm-clt}
### 中心極限定理

確率変数 $X$ が**分散を持つ**とする。
確率変数 $X_1,\dotsc,X_N$ が独立で $X$ と同じ分布に従うとする。
また、確率変数 $Z$ は期待値0分散1の正規分布 $N(0,1)$ に従うものとする。
このとき、
\begin{align*}
\frac1{\sqrt{N\var{X}}}\left(\sum_{k=1}^N X_k-N\expt{X}\right)
&\overset{d}{\longrightarrow} Z\qquad\text{as } N\to\infty.
\end{align*}
:::

確率変数 $X_k$ を期待値0分散1に正規化した確率変数
\begin{align*}
Y_k &\coloneqq \frac{X_k -\expt{X}}{\sqrt{\var{X}}}
\end{align*}
を使うと、
\begin{align*}
\frac{\sum_k Y_k}{\sqrt{N}}
&= Z\qquad\text{as } N\to\infty
\end{align*}
と表せる。

## 特性関数

::: {#def-cf}
確率変数 $X$ について、特性関数 $\varphi_X\colon\mathbb{R}\to\mathbb{C}$ を以下で定義する。
\begin{align*}
\varphi_X(t) &\coloneqq \expt{\mathrm{e}^{itX}}.
\end{align*}
:::

::: {#thm-cf}
確率変数 $X,\,Y$ について
\begin{align*}
\varphi_X = \varphi_Y &\iff F_X = F_Y.
\end{align*}
:::

## 特性関数の応用

:::{#lem-normal}
### 正規分布の再生性

独立確率変数 $X\sim N(\mu_0,\,\sigma_0^2)$ と $Y\sim N(\mu_1,\,\sigma_1^2)$ について
$X+Y\sim N(\mu_0+\mu_1,\,\sigma_0^2+\sigma_1^2)$.
:::
:::{.proof}
\begin{align*}
\varphi_X(t) &= \mathrm{e}^{i\mu_0 t - \frac12\sigma_0^2 t^2}&
\varphi_Y(t) &= \mathrm{e}^{i\mu_1 t - \frac12\sigma_1^2 t^2}
\end{align*}
より、
\begin{align*}
\varphi_{X+Y}(t) &= \varphi_X(t)\varphi_Y(t) =
\mathrm{e}^{i(\mu_0+\mu_1) t - \frac12(\sigma_0^2+\sigma_1^2) t^2}
\end{align*}
であるが、これは $N(\mu_0+\mu_1,\,\sigma_0^2+\sigma_1^2)$ の特性関数である。
よって、@thm-cf より
$X+Y\sim N(\mu_0+\mu_1,\,\sigma_0^2+\sigma_1^2)$.
:::

:::{#lem-normal}
### ポアソン分布の再生性

独立確率変数 $X\sim \mathrm{Poisson}(\lambda_0)$ と $Y\sim \mathrm{Poisson}(\lambda_1)$ について
$X+Y\sim \mathrm{Poisson}(\lambda_0+\lambda_1)$.
:::
:::{.proof}
\begin{align*}
\varphi_X(t) &= \mathrm{e}^{\lambda_0(\mathrm{e}^{it}-1)}&
\varphi_Y(t) &= \mathrm{e}^{\lambda_1(\mathrm{e}^{it}-1)}&
\end{align*}
より、
\begin{align*}
\varphi_{X+Y}(t) &= \varphi_X(t)\varphi_Y(t) =
\mathrm{e}^{(\lambda_0+\lambda_1)(\mathrm{e}^{it}-1)}&
\end{align*}
であるが、これは $\mathrm{Poisson}(\lambda_0+\lambda_1)$ の特性関数である。
よって、@thm-cf より
$X+Y\sim \mathrm{Poisson}(\lambda_0+\lambda_1)$.
:::

## レヴィの連続性定理

中心極限定理の証明の概要を紹介する。

@thm-cf は特性関数が確率分布と一対一に対応していることを主張していた。

:::{#thm-levy}
### レヴィの連続性定理

確率変数の列 $(X_n)_{n=1,2,\dotsc,}$ を考える。これらの確率変数は確率空間 $(\Omega,\,P)$ を共有している必要はない(同時確率を考えるわけではないので)。
確率変数列の特性関数列 $(\varphi_{X_n})_{n=1,2,\dotsc}$ が各点収束すると仮定する。
このとき、

\begin{align*}
\varphi(t) &\coloneqq \lim_{n\to\infty} \varphi_{X_n}(t).
\end{align*}

とおくと、ある確率変数 $X$ が存在し、$\varphi_X(t) = \varphi(t)$ であり、$(X_n)_n$ は $X$ に法則収束する。
:::

## テイラーの定理
:::{#thm-taylor}
### テイラーの定理
実関数 $f\colon \mathbb{R}\to\mathbb{R}$ が $a\in\mathbb{R}$ で $k\ge 1$ 回微分可能なとき、ある関数 $h\colon\mathbb{R}\to\mathbb{R}$ で $\lim_{x\to a}h(x) = 0$ であるものが存在し、
\begin{align*}
f(x) &= \sum_{s=0}^k\frac{f^{(s)}(a)}{s!}(x-a)^s + h(x)(x-a)^k.
\end{align*}
:::

## 中心極限定理の証明の概要

@thm-levy より
\begin{align*}
\lim_{N\to\infty} \varphi_{\frac{\sum_k Y_k}{\sqrt{N}}}(t) &= \varphi_Z(t) = \mathrm{e}^{-\frac{t^2}2}
\end{align*}
を示せば十分である。

\begin{align*}
\varphi_{\frac{\sum_k Y_k}{\sqrt{N}}}(t)
&= \varphi_{\sum_k Y_k}\left(\frac{t}{\sqrt{N}}\right)\\
&= \varphi_{Y}\left(\frac{t}{\sqrt{N}}\right)^N\\
&= \left(\varphi_Y(0) + \varphi'_Y(0)\frac{t}{\sqrt{N}} + \frac{\varphi''_Y(0)}2 \left(\frac{t}{\sqrt{N}}\right)^2 + o\left(\frac{1}{N}\right)\right)^N\\
&= \left(1 - \frac{1}2 \frac{t^2}{N} + o\left(\frac{1}{N}\right)\right)^N\\
&\to \mathrm{e}^{-\frac{t^2}2}.
\end{align*}


## 今週の課題

表が出る確率が $p$ のコインを $N$ 回投げて表が出る回数が区間 $\left[pN-a\sqrt{N},\, pN+a\sqrt{N}\right]$ に入る確率が $N\to\infty$ 極限で
\begin{align*}
\int_{-b}^b\frac1{\sqrt{2\pi}} \mathrm{e}^{-\frac12 x^2}\mathrm{d}x
\end{align*}
に収束するような $b>0$ を $p$ と $a$ を使って表せ。
