---
title: "確率論"
subtitle: "定常分布"
author: "森 立平"
format:
  revealjs:
    slide-number: true
    smaller: true
    html-math-method: mathjax
    include-in-header: macros.qmd
css: slides.css
---

## スペクトル半径 1/2
::: {#def-spectral}
### スペクトル半径
正方行列 $A\in\mathbb{C}^{n\times n}$ について、その固有値の絶対値の最大値を**スペクトル半径**といい $\rho(A)$ で表す
。
:::

::: {.callout-caution}
**スペクトルノルム**はスペクトル半径と似た概念であるが異なるものである。
正方行列とは限らない行列 $A\in\mathbb{C}^{n\times m}$ のスペクトルノルムは
\begin{align*}
\|A\|_2&\coloneqq \max_{x\in\mathbb{C}^m \setminus\{0\}} \frac{\|Ax\|_2}{\|x\|_2}
\end{align*}
と定義される。
ここで、右辺の $\|\cdot\|_2$ は複素ユークリッド空間上の **$L_2$ ノルム**を表す。ここで、
\begin{align*}
\|A\|_2&=
\max_{x\in\mathbb{C}^m \setminus\{0\}} \left\|A\frac{x}{\|x\|_2}\right\|_2\\
&=\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} \left\|Ax\right\|_2\\
&=\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} \sqrt{\left\|Ax\right\|_2^2}\\
&=\sqrt{\max_{x\in\mathbb{C}^m\colon\, \|x\|_2=1} x^*A^*Ax}\\
&=\sqrt{\lambda_{\max}(A^*A)}\\
&=\sigma_{\max}(A)
\end{align*}
である。$\lambda_{\max}$ と $\sigma_{\max}$ は最大固有値と最大特異値を表す。
:::

## スペクトル半径 2/2
::: {.callout-caution}
直感的な意味としては

* スペクトルノルム$\colon$ 線形写像 $A$ が $L_2$ ノルムをどれだけ大きくするか？
* スペクトル半径 $\colon$ 線形写像 $A$ が**向きを変えずに** $L_2$ ノルムをどれだけ大きくするか？

ということになる。
これらの意味から $\|A\|_2\ge\rho(A)$ であることが分かる。
実際 $\|A\|_2$ の定義の中で $x$ として $A$ の絶対値最大固有値に対応する固有ベクトルを選べばこの不等式が得られる。

正方行列 $A\in\mathbb{C}^{n\times n}$ が**正規行列**のとき、スペクトル分解定理よりユニタリ行列 $U$ と対角行列 $D$ を用いて $A = UDU^*$ と表せる。
このとき、$A^*A=UD^*DU^*$ であることから、簡単な計算により $\|A\|_2=\rho(A)$ であることが分かる。

しかし一般的には(対角化可能であっても)スペクトル半径とスペクトルノルムは異なる。
例えば、
\begin{align*}
A&=\begin{bmatrix}
1&0\\
1&0
\end{bmatrix}
\end{align*}
とすると、 $A$ の固有値は 0 と 1 なので$\rho(A)=1$ である。
一方で、
\begin{align*}
A^*A&=
\begin{bmatrix}
2&0\\
0&0
\end{bmatrix}
\end{align*}
より、$A^*A$ の固有値は 0 と 2 である。
よって、$A$ のスペクトルノルムは $\|A\|_2=\sqrt{2} > 1 =\rho(A)$ である。
ここで、$A$ は確率行列であり、二つの異なる固有値を持つので対角化可能である。
また、スペクトル半径はノルムにもならない。
\begin{align*}
\rho\left(\begin{bmatrix}0&1\\0&0\end{bmatrix}\right) &= 0
\end{align*}
であるし、
\begin{align*}
1&=\rho\left(\begin{bmatrix}0&1\\1&0\end{bmatrix}\right) >
\rho\left(\begin{bmatrix}0&1\\0&0\end{bmatrix}\right) +
\rho\left(\begin{bmatrix}0&0\\1&0\end{bmatrix}\right) = 0
\end{align*}
なので三角不等式も満たさない。
:::

::: {#lem-spectral}
任意の確率行列 $T$ について、$\rho(T)=1$ である。
:::
::: {.proof}
すべての成分が1の列ベクトルは確率行列 $T$ の固有値1に対する右固有ベクトルになるので、$\rho(T)\ge 1$ である。

以下では $\rho(T)\le 1$ を示す。
遷移行列 $T$ の固有値 $\lambda\in\mathbb{C}$ に対応する固有ベクトルを $v$ とすると
\begin{align*}
Tv &= \lambda v
\end{align*}
が成り立つ。
$v$ の成分で絶対値最大のものを第 $i$ 成分とする。
第 $i$ 成分に注目すると
\begin{align*}
\sum_{j\in S}T_{i,j}v_j &= \lambda v_i
\end{align*}
が成り立つ。ここで
\begin{align*}
|\lambda| |v_i| &= \left|\sum_{j\in S}T_{i,j}v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_i\right|\\
&=\left|v_i\right|
\end{align*}
と $|v_i|>0$ より、 $|\lambda|\le 1$ である。
:::

## 確率行列のスペクトル半径
::: {#lem-spectral}
任意の確率行列 $T$ について、$\rho(T)=1$ である。
:::
::: {.proof}
すべての成分が1の列ベクトルは確率行列 $T$ の固有値1に対する右固有ベクトルになるので、$\rho(T)\ge 1$ である。

以下では $\rho(T)\le 1$ を示す。
遷移行列 $T$ の固有値 $\lambda\in\mathbb{C}$ に対応する固有ベクトルを $v$ とすると
\begin{align*}
Tv &= \lambda v
\end{align*}
が成り立つ。
$v$ の成分で絶対値最大のものを第 $i$ 成分とする。
第 $i$ 成分に注目すると
\begin{align*}
\sum_{j\in S}T_{i,j}v_j &= \lambda v_i
\end{align*}
が成り立つ。ここで
\begin{align*}
|\lambda| |v_i| &= \left|\sum_{j\in S}T_{i,j}v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_j\right|\\
&\le \sum_{j\in S}T_{i,j}\left|v_i\right|\\
&=\left|v_i\right|
\end{align*}
と $|v_i|>0$ より、 $|\lambda|\le 1$ である。
:::



## 定常分布
マルコフ連鎖の推移行列 $T$ について、
\begin{align*}
\mu T &= \mu
\end{align*}
を満たす確率ベクトル(非負で成分の和が1) $\mu$ を**定常分布**と呼ぶのであった。
今回は**定常分布の存在と唯一性**について考える。

:::{#def-digraph}
### 有向グラフ
有限集合 $V$ と集合 $E\subseteq V\times V$ のペア $G=(V,\,E)$ を有向グラフという。
$V$ の元を**頂点**、$E$ の元を**辺(有向辺)**と呼ぶ。
:::

有向辺 $(u,v)\in E$ は頂点 $u$ から頂点 $v$ への有向辺と解釈することにする。
```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 有向グラフ $G=(V=\{1,2,3,4,5\},\, E=\{(1,2),\,(2,3),(2,4),\,(2,5),\,(3,1),\,(3,4),\,(4,2),\,(4,4),\,(5,1)\})$
digraph irreduc_graph {
  graph [rankdir=LR];
  node [shape=circle, width=0.1, fontsize=20];

  1 -> 2;
  2 -> 3;
  2 -> 4;
  3 -> 1;

  3 -> 4;
  4 -> 2;
  2 -> 5;
  5 -> 1;
  4 -> 4;
}
```

## 遷移グラフ
:::{#def-trgraph}
### 遷移グラフ
有向グラフ $G=(V,\,E)$ が状態集合 $S$ 上のマルコフ連鎖の遷移行列 $T$ の**遷移グラフ** $\defiff$
\begin{align*}
V&= S\\
E&=\left\{(u,v)\in V\times V\mid T_{u,v}>0\right\}.
\end{align*}
:::

マルコフ連鎖の定常分布や収束に関する議論をする際には遷移確率は 0 か正かということが問題になり、具体的な値は問題にならない。
したがって、定常分布が唯一であるための条件などは遷移グラフの性質として表すことができる。


:::{#def-cycle}
### 有向グラフのウォーク
有向グラフ $G=(V,E)$ の頂点列
\begin{align*}
(v_0,v_1,\dotsc,v_\ell)
\end{align*}
で各 $i=0,1,\dotsc,\ell-1$ について $(v_i,\,v_{i+1})\in E$ を満たすものを**($v_0$ から $v_{\ell}$ への)ウォーク**という。
また、$\ell$ をウォークの**長さ**という。
:::

頂点列 $(v)$ は長さ0のウォークであることに気をつけよう。
遷移グラフの定義より、任意の $u,v\in S$ について
\begin{align*}
&\text{遷移グラフ上に $u$ から $v$ への長さ $\ell$ のウォークが存在する} \iff (T^\ell)_{u,v} > 0\\
\iff&\Pr(X_\ell=v\mid X_0=u) > 0
\end{align*}
である。


## 既約性と定常分布

:::{#def-equiv}
### 順序関係
推移行列 $T$ を持つマルコフ連鎖の状態 $u,v\in S$ について $u\le_T v$ $\defiff$ その遷移グラフにおいて $u$ から $v$ へのウォークが存在する。
また、$u\le_T v$ かつ $v\le_T u$ のとき、$u\sim_T v$ とする。
:::

この $\le_T$ は以下の**前順序関係**の公理を満たす。

* (反射律) $\forall u\in S,\, u\le_T u$.
* (推移律) $\forall u,v,w\in S,\, (u\le_T v\,\land\, v\le_T w) \implies u\le_T w$.

また、$\sim_T$ は以下の**同値関係**の公理を満たす。

* (反射律) $\forall u\in S,\, u\sim_T u$.
* (対称律) $\forall u,v\in S,\, u\sim_T v\implies v\sim_T u$.
* (推移律) $\forall u,v,w\in S,\, (u\sim_T v\,\land\, v\sim_T w) \implies u\sim_T w$.


::: {#def-irred}
### マルコフ連鎖の既約性

マルコフ連鎖が**既約**である $\defiff$
任意の $u,v\in S$ について $u\sim_T v$.
<!--
任意の $x,y\in S$ についてある $t\in\mathbb{Z}_{\ge 0}$ が存在して、
\begin{align*}
\Pr(X_t=y\mid X_0 = x)&>0
\end{align*}
$\iff$
任意の $x,y\in S$ についてある $t\in\mathbb{Z}_{\ge 0}$ が存在して、$(T^t)_{x,y}>0$.
-->
:::

有向グラフ $G$ の任意の頂点 $u, v\in V$ について $u$ から $v$ へのウォークが存在するとき、$G$ は**強連結**であるという。
よってマルコフ連鎖が既約 $\iff$ 遷移グラフが強連結である。

```{dot}
//| fig-width: 5
//| fig-height: 1.2
//| fig-cap: 既約なマルコフ連鎖の遷移グラフ。任意の頂点 $u, v\in V$ について、$u$ から $v$ へのウォークが存在する。
digraph irreduc_graph {
  graph [rankdir=LR];
  node [shape=circle, width=0.1, fontsize=20];

  1 -> 2;
  2 -> 3;
  2 -> 4;
  3 -> 1;

  3 -> 4;
  4 -> 2;
  2 -> 5;
  5 -> 1;
  4 -> 4;
}
```

## 既約なマルコフ連鎖
::: {#lem-irred}
既約なマルコフ連鎖について $\mathrm{Ker}(I-T)=\mathrm{span}(\mathbf{1})$ である。
ここで$\mathbf{1}$はすべての成分が1の列ベクトルとする。
:::
::: {.proof}
列ベクトル $v\in\mathbb{R}^n$ を
\begin{align*}
(I-T)v = 0 &\iff Tv = v
\end{align*}
を満たすものとする。
このとき、$i\in\arg\max_{k\in S} v_k$ とすると
\begin{align*}
v_i &= \sum_{j\in S} T_{i,j} v_j\\
&= \sum_{j\in S\colon\,(i,j)\in E} T_{i,j} v_j\\
&\le \sum_{j\in S\colon\,(i,j)\in E} T_{i,j} v_i\\
&= v_i
\end{align*}
という不等式が得られる。
この不等号は等号でなくてはいけないので、
\begin{align*}
v_j &= v_i\qquad\text{if } (i, j)\in E
\end{align*}
である。
この議論を繰り返すと $i\le_T j$ である $j$ について $v_j=v_i$ である。
マルコフ連鎖が既約であることから、任意の $j\in S$ について $i\le_T j$ であり、$v = v_i \mathbf{1}$ である。
したがって、$\mathrm{Ker}(I-T)=\mathrm{span}(\mathbf{1})$ である。
:::

よって**既約なマルコフ連鎖に対して定常分布は高々一つ**である。
実際には既約なマルコフ連鎖は一つの定常分布を持つ。

## 既約なマルコフ連鎖の定常分布
::: {#thm-irred}
既約なマルコフ連鎖は**唯一の定常分布** $\mu\in\mathbb{R}_{>0}^n$ を持つ。
:::
:::{.proof}
マルコフ連鎖の**ラプラシアン行列**を $\Lambda \coloneqq I-T$ と定義する。
ラプラシアン行列の余因子行列を $\mathrm{adj}(\Lambda)$ で表す($\mathrm{adj}(\Lambda)$ の $(i,j)$ 成分は $(j,i)$ 余因子である)。
余因子展開より
\begin{align*}
\mathrm{adj}(\Lambda)\Lambda &= \Lambda\,\mathrm{adj}(\Lambda) = \det(\Lambda)I
\end{align*}
である。確率行列 $T$ は固有値1を持つので、$\det(\Lambda)=0$ である。
よって、
\begin{align*}
\mathrm{adj}(\Lambda)\Lambda &= \Lambda\,\mathrm{adj}(\Lambda) = O
\end{align*}
である。
まず、$\Lambda\,\mathrm{adj}(\Lambda)=O$ と @lem-irred より $\mathrm{adj}(\Lambda)$ の各列は $\mathbf{1}$ のスカラー倍である。よって、$\mathrm{adj}(\Lambda)$ の行はすべて等しい。
次に、$\mathrm{adj}(\Lambda)\Lambda=O$ より、$\mathrm{adj}(\Lambda)$ の行 $\mu\in\mathbb{R}^n$ は $\mu\Lambda=0$ を満たす。
ここで、$\mathrm{adj}(\Lambda)$ の行がすべて等しいことから
\begin{align*}
\mu_i &= \mathrm{adj}(\Lambda)_{i,i}\qquad\forall i\in S
\end{align*}
が成り立つ。
よって
\begin{align*}
\mathrm{adj}(\Lambda)_{i,i}&>0\qquad\forall i\in S
\end{align*}
を示せば十分である。
余因子行列の定義より、
\begin{align*}
\mathrm{adj}(\Lambda)_{i,i}&= \det(I - T^{(i)})
\end{align*}
である。
ここで、$T^{(i)}$ は $T$ の $i$ 行目と $i$ 列目を削除して得られる行列である。

目標である $\det(I-T^{(i)})>0$ を示すためには $\rho(T^{(i)})<1$ を示せば十分である。
:::

## スペクトル半径と行列式

::: {#lem-spectral-det}
任意の実正方行列 $A$ について、$\rho(A)<1$ ならば $\det(I-A)>0$ である。
:::

::: {.callout-note}
### 代数的な証明
実正方行列 $A$ の固有値の多重集合を $\mathrm{spec}(A)$ で表すことにする。
実多項式の実数でない根はその複素共役とペアで現れることに注意すると、
\begin{align*}
\det(I-A)&= \prod_{\lambda\in\mathrm{spec}(A)} (1-\lambda)\\
&= \prod_{\lambda\in\mathrm{spec}(A)\cap\mathbb{R}} (1-\lambda)
\cdot \prod_{\lambda\in\mathrm{spec}(A)\setminus\mathbb{R}} (1-\lambda)\\
&= \prod_{\lambda\in\mathrm{spec}(A)\cap\mathbb{R}} (1-\lambda)
\cdot \prod_{\lambda\in\mathrm{spec}(A)\setminus\mathbb{R}} |1-\lambda|\\
\end{align*}
よって $\rho(A)<1$ であれば $\det(I-A)>0$ である。
:::

::: {.callout-note}
### 解析的な証明
実正方行列 $A$ の特性多項式を
\begin{align*}
p_A(x) &\coloneqq \det(xI - A)
\end{align*}
と定義する。
これはモニックな多項式であるため $x\to+\infty$ で $p_A(x)\to+\infty$ である。
よって $p_A(x)$ が実根を持たないもしくは、すべての実根が 1 未満であれば $p_A(1)>0$ である。
特性多項式 $p_A$ の根は $A$ の固有値なので、$\rho(A)<1$ であれば $p_A(1)=\det(I-A)>0$ である。
:::

## 証明の続き

よって、$\rho(T^{(i)})<1$ を示せば $\mathrm{adj}(\Lambda)_{i,i}=\det(I-T^{(i)}) > 0$ がしたがう。

$T^{(i)}$ の絶対値最大の固有値を $\lambda$ とおき、対応する固有ベクトルを $v$ とする。
このとき
\begin{align*}
T^{(i)}v &= \lambda v
\end{align*}
が成り立つ。
$v$ の絶対値最大の成分のインデックスを $j\in S\setminus\{i\}$ とおく。
マルコフ連鎖が**既約**であることから、その遷移グラフ上で $j$ から $i$ へのウォークが存在する。
そのウォークの長さを $\ell\in\mathbb{Z}_{\ge 1}$ とおく。
このとき、$S\coloneqq T^{(i)\ell}$ とおくと、
\begin{align*}
S v &= \lambda^\ell v
\end{align*}
である。
ここで、$S$ の $j$ 行目の和は
\begin{align*}
\sum_k S_{j,k} &= \Pr(X_1\ne i,\dotsc,X_\ell \ne i\mid X_0 = j) < 1
\end{align*}
である。
よって、
\begin{align*}
|\lambda^\ell v_j| &= |(S v)_j|
= \left|\sum_{k}S_{j,k} v_k\right|\\
&\le \sum_{k}S_{j,k} \left|v_k\right|
\le \sum_{k}S_{j,k} |v_j| < |v_j|\\
\end{align*}
である。$|v_j|>0$ より、$|\lambda|<1$ である。
したがって、$\rho(T^{(i)}) < 1$ であることが示された。

## 一般のマルコフ連鎖の定常分布

次に既約とは限らない一般のマルコフ連鎖について考える。
マルコフ連鎖の状態集合 $S$ を同値関係 $\sim_T$ で割った同値類 $S/\sim_T$ を考える。
そして、その同値類の遷移グラフを考える。

:::{#def-digraph-equiv}
### 同値類の遷移グラフ
有向グラフ $G=(V,\,E)$ が状態集合 $S$ 上のマルコフ連鎖の遷移行列 $T$ の**遷移グラフ** $\defiff$
\begin{align*}
V&= S/\sim_T\\
E&=\left\{(A,B)\in V\times V\mid \exists a\in A, b\in B\quad T_{a,b}>0,\,A\ne B\right\}.
\end{align*}
:::

マルコフ連鎖の遷移グラフから同値類の遷移グラフは定まる。

:::{#def-digraph-scc}
### 強連結成分と縮約グラフ

有向グラフ $G=(V,E)$ について、$V$ 上の同値関係を $u\sim v\defiff \text{$u$ と $v$ の間に両方向のパスがある}$と定義す
る。
この同値関係の同値類を $G$ の**強連結成分**と呼ぶ。

$G$ の強連結成分を頂点に持つ**縮約グラフ** $G'=(V',E')$ を
\begin{align*}
V'&=V/\sim\\
E'&=\left\{(A,B)\in V'\times V'\mid \exists a\in A, \exists b\in B, (a,b)\in E, A\ne B\right\}
\end{align*}
と定義する。
:::

## 縮約グラフの例

```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 有向グラフの例。強連結ではない。
digraph tgraph {
  graph [rankdir=LR];
  node [shape=circle, width=0.1, fontsize=20];

  1 -> 2;
  2 -> 3;
  3 -> 1;

  2 -> 4;
  2 -> 5;
  5 -> 6;
  6 -> 5;
  4 -> 7;
  6 -> 7;
  1 -> 7;
  7 -> 7;
}
```
```{dot}
//| fig-width: 7
//| fig-height: 3
//| fig-cap: 上の図の有向グラフの縮約グラフ。
digraph tgraph_equiv {
  rankdir=LR;
  node [shape=circle, width=0.6, margin="0.01", fixedsize=true, fontsize=10];

  a [label="{1, 2, 3}"]
  b [label="{4}"]
  c [label="{5, 6}"]
  d [label="{7}"]

  a -> b;
  a -> d;
  a -> c;
  b -> d;
  c -> d;
}
```

## 再帰的な状態と一般のマルコフ連鎖の定常分布

DAG(サイクルを持たない有向グラフ)の頂点で出次数(外に出ていく有向辺の個数)が0のものをシンクという。
(有限サイズの)DAGは必ずシンクを一つ以上持つ。
一般のマルコフ連鎖の定常分布について、その同値類の遷移グラフを用いて考察する。
マルコフ連鎖の同値類の遷移グラフにおいてシンクに対応する同値類やそれに含まれる状態を**再帰的**であるという。

以下、簡単に一般のマルコフ連鎖の定常分布について概要を説明する。

:::{#lem-stat-trans}
マルコフ連鎖の定常分布を $\mu\in\mathbb{R}^n$ とすると、再帰的でない状態 $s\in S$ について $\mu(s)=0$ である。
:::
:::{.proof}
(証明の概要)
再帰的でない状態 $s$ が正の確率 $\mu(s)>0$ を持つ定常分布が存在すると仮定する。
状態 $s$ から何らかの再帰的な状態 $t$ へ正の確率で遷移する。よってマルコフ連鎖を進めることで、 $t$ が属する同値類の確率の総和が増加する。
定常分布はマルコフ連鎖の遷移で変化しない分布であるので、これは矛盾である。
:::

よって、一般的なマルコフ連鎖の定常分布を考える上では再帰的でない状態は存在しないものとして考えることができる。
再帰的な同値類は互いに遷移できない。また、再帰的な同値類それぞれに唯一の定常分布が存在する。
そして、それらの凸結合(確率混合)もまた定常分布である。
これらですべての定常状態を表すことができる。
これがマルコフ連鎖の定常分布の一般論である。


## 今週の課題

以下の推移行列を持つマルコフ連鎖の遷移グラフを描け。
状態のラベルは行と列のインデックスに対応して $1,2,\dotsc,$ の順番で付けるとする。
また、それぞれのマルコフ連鎖が既約であるか判定せよ。
既約である場合は「既約である」、
既約でない場合は「状態 $i$ から状態 $j$ へ遷移できないため既約でない」と記せ。
既約でないことを示すための状態ペア $(i,\,j)$ は一つ示せばよい。

:::{style="font-size:0.8em"}
1.
\begin{align*}
\begin{bmatrix}
1/2&1/3&1/6\\
1/4&1/2&1/4\\
1/3&1/3&1/3
\end{bmatrix}.
\end{align*}
1.
\begin{align*}
\begin{bmatrix}
0&1&0\\
0&0&1\\
1&0&0
\end{bmatrix}.
\end{align*}
1.
\begin{align*}
\begin{bmatrix}
1/2&1/2&0\\
0&1/2&1/2\\
0&0&1
\end{bmatrix}.
\end{align*}
1.
\begin{align*}
\begin{bmatrix}
1/2&1/2&0&0\\
1/3&2/3&0&0\\
0&0&0&1\\
0&0&1&0
\end{bmatrix}.
\end{align*}
:::
